logging:
  level:
    root: INFO

iobackend:
  jwtkey: ${BASE64_IO_JWT_KEY:Cup7DtbwoctKZqDJun/kkVLs4TSdHCRzVzA5L5PrXQg=}


management.endpoints.web.exposure.include: health,metrics
management:
  endpoint:
    health:
      probes:
        enabled: true