logging:
  level:
    root: INFO

spring.application.name: mockio-local # allows to get proper resource name on otel
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  defaults:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

iobackend:
  jwtkey: ${BASE64_IO_JWT_KEY:Cup7DtbwoctKZqDJun/kkVLs4TSdHCRzVzA5L5PrXQg=}

applicationinsights:
  connection:
    string: ${APPINSIGHT_CONNECTION_STRING}
