logging:
  level:
    root: INFO

iobackend:
  jwtkey: ${BASE64_IO_JWT_KEY:testKey}


management.endpoints.web.exposure.include: health,metrics
management:
  endpoint:
    health:
      probes:
        enabled: true