logging:
  level:
    root: INFO

spring.application.name: mockio # allows to get proper resource name on otel

otel.instrumentation.logback-appender.enabled: true
otel.exporter.otlp.enabled: false
otel.traces.sampler.probability: 1.0
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints.web.exposure.include: health,metrics
  endpoint:
    health:
      probes:
        enabled: true

iobackend:
  jwtkey: ${BASE64_IO_JWT_KEY:lOZ35qyOUbxFK4NPcyVoRqzOUt7J3nEyTfDeCMxRi2i2dulEYC1klIboJpXhXE3J}

applicationinsights.connectionstring: ${APPINSIGHTS_CONNECTION_STRING}
