microservice-chart:
  image:
    repository: cstardcommonacr.azurecr.io/cstariomock
    tag: latest
    pullPolicy: Always

  ingress:
    host: "dev01.rtd.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "128Mi"
      cpu: "2000m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    cooldownPeriod: 30 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "60"

  keyvault:
    name: "cstar-d-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
