microservice-chart:
  image:
    repository: cstardcommonacr.azurecr.io/cstariomock
    tag: latest
    pullPolicy: Always

  ingress:
    host: "dev01.rtd.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url

  envConfig:
    AZURE_REQUEST_RESPONSE_TIMEOUT: "30000"
    AZURE_REQUEST_WRITE_TIMEOUT: "30000"
    AZURE_REQUEST_READ_TIMEOUT: "30000"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    cooldownPeriod: 30 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
              - type: Pods
                value: 1
                periodSeconds: 2

  keyvault:
    name: "cstar-d-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
