parameters:
  - name: environment
    type: string
  - name: dockerRegistryServiceConnection
    type: string
  - name: vmImageName
    type: string
  - name: k8sImageRepository
    type: string
  - name: executeBuild
    type: boolean

jobs:
  - job: Build
    displayName: "Build and publish to $(environment)"
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
      - task: Docker@2
        condition: and(succeeded(), ${{ parameters.executeBuild }})
        displayName: 'Publish image to $(environment)'
        inputs:
          containerRegistry: '${{ parameters.dockerRegistryServiceConnection }}'
          repository: '${{ parameters.k8sImageRepository }}'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
            $(projectVersion)