parameters:
  - name: environment
    type: string
  - name: dockerRegistryServiceConnection
    type: string
  - name: k8sImageRepository
    type: string

steps:
  - task: Docker@2
    condition: and(succeeded(), ${{ parameters.executeBuild }})
    displayName: 'Publish image to ${{ parameters.environment }}'
    inputs:
      containerRegistry: '${{ parameters.dockerRegistryServiceConnection }}'
      repository: '${{ parameters.k8sImageRepository }}'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
        ${{ variables.projectVersion }}