name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

permissions:
  packages: write
  contents: write


jobs:
  checkout:
    name: 🔖 Checkout Repository
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.ref_name }}

  flow-release:
    name: 🚀 Release
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - name: 🚀 release + docker
        # https://github.com/pagopa/github-actions-template/releases/tag/v2.4.1
        uses: pagopa/github-actions-template/payments-flow-release@713f5abd8f8ee210e5f6a4243ae52eb7c1b3b5ab
        with:
          current_branch: ${{ github.ref_name }}
